"""Stable SSRS portal selectors. Fragile generated Angular classes are avoided."""

USERNAME = "input[type='email'], input[name*='user' i], input[id*='user' i]"
PASSWORD = "input[type='password']"
SUBMIT = "button[type='submit'], input[type='submit']"
LINKS = "a[href]"
PORTAL_MARKERS = "html#portal, base[href*='/Reports/'], user-info, folder-tile, report-tile"
READY_MARKERS = "section.items, folder-tile, report-tile, #currentfolder-heading"
CURRENT_FOLDER = "#currentfolder-heading"
FOLDER_LINKS = "folder-tile a.tile[href^='browse/'], folder-tile a.tile[href*='/browse/']"
REPORT_LINKS = "report-tile a.tile[href^='report/'], report-tile a.tile[href*='/report/']"
TILE_NAME = "span.multiline-ellipsis"
CONTEXT_MENU = "report-tile a.context[role='button']"
DOWNLOAD_MENU_ITEMS = "[role='menuitem'][aria-label*='download' i], a[aria-label*='download' i]"
